# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9BRUZD522hqLzB0QS8uWvAyFcHxk-P4
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

data=pd.read_csv("linear_model.csv",sep=",")

data.y.fillna(value=data.y.mean(), inplace=True)

data.head

data.shape

x=data["x"]
y=data["y"]

plt.scatter(x,y)
plt.xlabel("X ekseni")
plt.ylabel("Y ekseni")
plt.show()





x=data["x"].values.reshape((100,1))
y=data["y"].values.reshape((100,1))

x.shape
y.shape

model= LinearRegression()
model.fit(x,y)

sns.regplot(x="x",y="y",data=data,line_kws={"color":"red"})

model.predict([[17]])

model.predict([[70]])

model.score(x,y)

